In [1]:
import numpy as np

In [2]:
l = [1,2,3,4,4]

In [3]:
type(l)

list

In [4]:
a = np.array(l)

In [5]:
type(a)

numpy.ndarray

In [6]:
a

array([1, 2, 3, 4, 4])

In [7]:
a1 = np.array([[1,2,3],[3,4,5]])

In [8]:
a1

array([[1, 2, 3],
       [3, 4, 5]])

In [9]:
a2 = np.array([[[1,2,3],[4,5,6]]])

In [10]:
a2

array([[[1, 2, 3],
        [4, 5, 6]]])

In [11]:
a

array([1, 2, 3, 4, 4])

In [12]:
a1

array([[1, 2, 3],
       [3, 4, 5]])

In [13]:
a2

array([[[1, 2, 3],
        [4, 5, 6]]])

In [14]:
# to check dimention we used --> ndim
a.ndim

1

In [15]:
a1.ndim

2

In [16]:
a2.ndim

3

In [20]:
a3 = np.array([[[1,2,3],[4,.5,6]],[[1,2,3],[4,.5,6]],[[1,2,3],[4,.5,6]]])

In [21]:
a3

array([[[1. , 2. , 3. ],
        [4. , 0.5, 6. ]],

       [[1. , 2. , 3. ],
        [4. , 0.5, 6. ]],

       [[1. , 2. , 3. ],
        [4. , 0.5, 6. ]]])

In [22]:
a3.ndim

3

In [23]:
l = [1,2,3,4]

In [30]:
a = np.asarray(l)

In [31]:
m = np.matrix(l)

In [32]:
np.asanyarray(a)

array([1, 2, 3, 4])

In [33]:
np.asanyarray(m)

matrix([[1, 2, 3, 4]])

In [34]:
a 

array([1, 2, 3, 4])

In [35]:
# this is shallow copy
a1=a

In [36]:
a1

array([1, 2, 3, 4])

In [37]:
a

array([1, 2, 3, 4])

In [38]:
a[0] = 10

In [39]:
a

array([10,  2,  3,  4])

In [40]:
a1

array([10,  2,  3,  4])

In [41]:
a1[3] = 50

In [42]:
a1

array([10,  2,  3, 50])

In [43]:
# if we change value of a is also change value in a1 and
# if we change value of a1 is also change value in a 
a

array([10,  2,  3, 50])

In [44]:
# with the help of ---> np.copy() we can solve this problem
# in that we can change value of a it can't be change in a1


# This is an example of Deep copy
a2 = np.copy(a)

In [45]:
a2

array([10,  2,  3, 50])

In [46]:
a2[2] = 30

In [47]:
a2

array([10,  2, 30, 50])

In [48]:
a

array([10,  2,  3, 50])

In [49]:
np.fromfunction(lambda i,j : i==j, (3,4))

array([[ True, False, False, False],
       [False,  True, False, False],
       [False, False,  True, False]])

above example explanation is like  i==j means 0==0 or 1==1 or 2==2

   0   1   2   3 

0  T   F   F   F

1  F   T   F   F

2  F   F   T   F

In [52]:
np.random.rand(2,3)  # In that 2 is for rows and 3 is for column

array([[0.71675862, 0.00462938, 0.66256455],
       [0.16479207, 0.43477507, 0.64664063]])

In [54]:
np.random.rand(2,3,2)   # in that first 2 is for how many matrix is generate , 3 is for rows and 2 is for columns

array([[[0.65026627, 0.17266235],
        [0.12988086, 0.51300503],
        [0.47233892, 0.33736556]],

       [[0.84166254, 0.0710585 ],
        [0.3857605 , 0.3181259 ],
        [0.0120269 , 0.1722699 ]]])

In [55]:
np.random.rand(3,2,2)

array([[[0.52316535, 0.06556437],
        [0.75476052, 0.29984199]],

       [[0.08715446, 0.07942339],
        [0.5211738 , 0.85818294]],

       [[0.27503722, 0.16743214],
        [0.44113087, 0.21822173]]])

In [61]:
# meaning is that take some random data  0 to 10 and in bracket
# we specify a number that which type of matrix is want like 2*2 or 3*3 
np.random.randint(0,10,(4,4))

array([[7, 8, 9, 9],
       [4, 7, 6, 1],
       [9, 6, 5, 6],
       [4, 9, 6, 5]])

In [62]:
np.random.randint(0,10,(4,4,2))

array([[[4, 9],
        [5, 7],
        [3, 2],
        [1, 7]],

       [[7, 6],
        [7, 9],
        [8, 8],
        [9, 8]],

       [[5, 0],
        [4, 6],
        [5, 5],
        [4, 7]],

       [[9, 2],
        [2, 6],
        [0, 6],
        [4, 4]]])

In [64]:
np.random.randn(3,4,4)

array([[[-1.98189589, -0.75639847, -1.13029827, -0.35603242],
        [-0.23465308, -0.01758352,  0.90999741,  0.07048916],
        [-1.739     , -1.31410295,  1.64523826,  1.42318626],
        [ 0.12080157, -0.26947229,  0.28966772, -1.58400165]],

       [[ 1.73814423, -0.36079528,  0.23736246,  2.08944589],
        [ 0.66898612, -0.22205837, -0.51202547,  0.52925017],
        [ 3.43729499,  0.36345599, -0.28209295,  0.14875408],
        [ 1.99396758,  0.52655197, -0.58241337,  0.37082549]],

       [[ 0.14511728, -2.49237586,  0.09971832, -0.78228637],
        [ 0.1890053 , -0.72497205, -2.0003708 , -0.45065193],
        [-1.04952253,  1.48845921, -0.11937295, -1.49585817],
        [-1.04516395, -0.80718052, -0.53911724,  0.70153981]]])

In [65]:
d = np.random.randn(3,4) 

In [66]:
import pandas as pd

In [68]:
# Convert 3*4 into Dataframe
pd.DataFrame(d)

0         1         2         3
0 -2.092014 -0.092623 -0.428598  0.429877
1  0.438451 -0.741940 -1.550148 -0.425547
2  1.543333  0.644303  1.656162 -0.626546

In [73]:
d1 = np.random.randint(0,10,(4,4,2))

In [76]:
# How to convert this into DataFrame ansswer in next cell
# to convert this into DataFrame we use reshape() Function
d1

array([[[7, 8],
        [1, 9],
        [8, 4],
        [9, 1]],

       [[5, 4],
        [5, 2],
        [1, 1],
        [7, 3]],

       [[6, 9],
        [5, 5],
        [9, 9],
        [1, 8]],

       [[8, 8],
        [3, 0],
        [4, 5],
        [7, 5]]])

In [80]:
d1.reshape(8,4)  # we take 8 * 4 because in that 32 element arre present that why we take multiplication of this number

array([[7, 8, 1, 9],
       [8, 4, 9, 1],
       [5, 4, 5, 2],
       [1, 1, 7, 3],
       [6, 9, 5, 5],
       [9, 9, 1, 8],
       [8, 8, 3, 0],
       [4, 5, 7, 5]])

In [81]:
d1.reshape(16,2) # same condition --> multiplication is always equal to number of element 

array([[7, 8],
       [1, 9],
       [8, 4],
       [9, 1],
       [5, 4],
       [5, 2],
       [1, 1],
       [7, 3],
       [6, 9],
       [5, 5],
       [9, 9],
       [1, 8],
       [8, 8],
       [3, 0],
       [4, 5],
       [7, 5]])

In [83]:
d1.reshape(16,-11343)  # at least give one correct dimention

array([[7, 8],
       [1, 9],
       [8, 4],
       [9, 1],
       [5, 4],
       [5, 2],
       [1, 1],
       [7, 3],
       [6, 9],
       [5, 5],
       [9, 9],
       [1, 8],
       [8, 8],
       [3, 0],
       [4, 5],
       [7, 5]])

In [84]:
d1.reshape(8,-324)

array([[7, 8, 1, 9],
       [8, 4, 9, 1],
       [5, 4, 5, 2],
       [1, 1, 7, 3],
       [6, 9, 5, 5],
       [9, 9, 1, 8],
       [8, 8, 3, 0],
       [4, 5, 7, 5]])

In [85]:
pd.DataFrame(d1.reshape(8,4))

0  1  2  3
0  7  8  1  9
1  8  4  9  1
2  5  4  5  2
3  1  1  7  3
4  6  9  5  5
5  9  9  1  8
6  8  8  3  0
7  4  5  7  5

In [86]:
pd.DataFrame(d1.reshape(8,-1223))

0  1  2  3
0  7  8  1  9
1  8  4  9  1
2  5  4  5  2
3  1  1  7  3
4  6  9  5  5
5  9  9  1  8
6  8  8  3  0
7  4  5  7  5

In [87]:
pd.DataFrame(d1.reshape(16,2))

0  1
0   7  8
1   1  9
2   8  4
3   9  1
4   5  4
5   5  2
6   1  1
7   7  3
8   6  9
9   5  5
10  9  9
11  1  8
12  8  8
13  3  0
14  4  5
15  7  5

In [88]:
pd.DataFrame(d1.reshape(16,-1))

0  1
0   7  8
1   1  9
2   8  4
3   9  1
4   5  4
5   5  2
6   1  1
7   7  3
8   6  9
9   5  5
10  9  9
11  1  8
12  8  8
13  3  0
14  4  5
15  7  5

In [90]:
pd.DataFrame(d1.reshape(32,-435553))

0
0   7
1   8
2   1
3   9
4   8
5   4
6   9
7   1
8   5
9   4
10  5
11  2
12  1
13  1
14  7
15  3
16  6
17  9
18  5
19  5
20  9
21  9
22  1
23  8
24  8
25  8
26  3
27  0
28  4
29  5
30  7
31  5

In [91]:
np.arange(0.5,10)

array([0.5, 1.5, 2.5, 3.5, 4.5, 5.5, 6.5, 7.5, 8.5, 9.5])

In [92]:
np.arange(10) # arange generate floating point number

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [95]:
list(range(10))   # range does not generate floating point number 

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [96]:
np.arange(5,-4,-1)

array([ 5,  4,  3,  2,  1,  0, -1, -2, -3])

In [98]:
np.arange(5,-4,-.5)

array([ 5. ,  4.5,  4. ,  3.5,  3. ,  2.5,  2. ,  1.5,  1. ,  0.5,  0. ,
       -0.5, -1. , -1.5, -2. , -2.5, -3. , -3.5])

In [100]:
# it means that generate 20 data between range 1 to 5 
np.linspace(1,5,20) 

array([1.        , 1.21052632, 1.42105263, 1.63157895, 1.84210526,
       2.05263158, 2.26315789, 2.47368421, 2.68421053, 2.89473684,
       3.10526316, 3.31578947, 3.52631579, 3.73684211, 3.94736842,
       4.15789474, 4.36842105, 4.57894737, 4.78947368, 5.        ])

In [101]:
# it means that generate 10 data between range 1 to 5 and it take logarithm num
np.logspace(1,5,10)

array([1.00000000e+01, 2.78255940e+01, 7.74263683e+01, 2.15443469e+02,
       5.99484250e+02, 1.66810054e+03, 4.64158883e+03, 1.29154967e+04,
       3.59381366e+04, 1.00000000e+05])

In [104]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [105]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [106]:
np.zeros((3,5,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [107]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [109]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [110]:
np.ones((3,4,2))

array([[[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]]])

In [111]:
np.ones((3,4,2)) + 5

array([[[6., 6.],
        [6., 6.],
        [6., 6.],
        [6., 6.]],

       [[6., 6.],
        [6., 6.],
        [6., 6.],
        [6., 6.]],

       [[6., 6.],
        [6., 6.],
        [6., 6.],
        [6., 6.]]])

In [112]:
np.ones((3,4,2)) * 5

array([[[5., 5.],
        [5., 5.],
        [5., 5.],
        [5., 5.]],

       [[5., 5.],
        [5., 5.],
        [5., 5.],
        [5., 5.]],

       [[5., 5.],
        [5., 5.],
        [5., 5.],
        [5., 5.]]])

In [118]:
np.empty((2,3))

array([[2., 0., 2.],
       [0., 2., 0.]])

In [121]:
# square matrix is ---> diagonal is 1
a = np.eye(4)

In [123]:
a.shape

(4, 4)

In [124]:
a.size

16

In [125]:
a.ndim

2

In [126]:
a1 = np.random.randn(3,4)

In [127]:
a1

array([[ 1.68649671,  2.15602321, -0.05864859, -0.24515284],
       [-1.09235992, -1.47930413,  0.6574236 , -0.22133255],
       [ 1.211394  ,  0.90683815,  0.84834253, -0.81632208]])

In [128]:
pd.DataFrame(a1)

0         1         2         3
0  1.686497  2.156023 -0.058649 -0.245153
1 -1.092360 -1.479304  0.657424 -0.221333
2  1.211394  0.906838  0.848343 -0.816322

In [129]:
 a1

array([[ 1.68649671,  2.15602321, -0.05864859, -0.24515284],
       [-1.09235992, -1.47930413,  0.6574236 , -0.22133255],
       [ 1.211394  ,  0.90683815,  0.84834253, -0.81632208]])

In [130]:
a1[1][1]

-1.4793041302233112

In [131]:
a1[0:2 , 0:2]

array([[ 1.68649671,  2.15602321],
       [-1.09235992, -1.47930413]])

In [133]:
a1[[0,1], 0:2]

array([[ 1.68649671,  2.15602321],
       [-1.09235992, -1.47930413]])

array([1.68649671, 0.6574236 ])

In [136]:
a1[[1,2],3]

array([-0.22133255, -0.81632208])

In [146]:
m1 = np.random.randint(1,3,(3,3))

In [147]:
m1

array([[1, 1, 1],
       [2, 2, 2],
       [1, 2, 2]])

In [148]:
m2 = np.random.randint(2,4, (3,3))

In [149]:
m2

array([[3, 2, 3],
       [2, 3, 3],
       [2, 3, 3]])

In [150]:
m1 * m2

array([[3, 2, 3],
       [4, 6, 6],
       [2, 6, 6]])

In [151]:
m1@m2   # @ is used for matrix multiplication

array([[ 7,  8,  9],
       [14, 16, 18],
       [11, 14, 15]])

In [152]:
m1

array([[1, 1, 1],
       [2, 2, 2],
       [1, 2, 2]])

In [153]:
m2

array([[3, 2, 3],
       [2, 3, 3],
       [2, 3, 3]])

In [154]:
m1


array([[1, 1, 1],
       [2, 2, 2],
       [1, 2, 2]])

In [155]:
pow(m1, 2)

array([[1, 1, 1],
       [4, 4, 4],
       [1, 4, 4]])

In [156]:
np.sqrt(m1)

array([[1.        , 1.        , 1.        ],
       [1.41421356, 1.41421356, 1.41421356],
       [1.        , 1.41421356, 1.41421356]])

In [157]:
np.log(m1)

array([[0.        , 0.        , 0.        ],
       [0.69314718, 0.69314718, 0.69314718],
       [0.        , 0.69314718, 0.69314718]])

In [158]:
np.log10(m1)

array([[0.     , 0.     , 0.     ],
       [0.30103, 0.30103, 0.30103],
       [0.     , 0.30103, 0.30103]])

In [159]:
np.exp(m1)

array([[2.71828183, 2.71828183, 2.71828183],
       [7.3890561 , 7.3890561 , 7.3890561 ],
       [2.71828183, 7.3890561 , 7.3890561 ]])

In [160]:
m1 ** 2

array([[1, 1, 1],
       [4, 4, 4],
       [1, 4, 4]])